### ISSUE TITLE
Recommendation - Provide 3mf file for PGC5-2S15 with separate objects

### ISSUE THREAD

**Issue by npanagop** [gearfinity/gearfinity#1]
Hello,

Great idea, hope this takes off!

I just printed the first part of the planetary gear set (PGC5-2S15). I had issues with the gear teeth getting stuck to each other. I know this is my fault because I printed on a new material which I haven't tuned for my printer yet.

Despite that, I believe it would be convenient for testing to have a .3mf file (PrusaSlicer project) with the gears placed in their respective positions already but as separate objects. The user would be able to scale them by a few percents to improve tolerances. 

Thank you.

**Comment by gearfinity** [comment]
Excellent suggestion! I also plan on providing different pre-set tolerances to try. The "15" in the PGC5-2S15 actually represents 0.15 mm tolerance in the openscad model that generates them. I'm not sure how different it would be to manually scale the gears themselves (I'm no expert in gear mechanics) but I agree it would be a good option to have if the pre-set options don't work.

Also, in my own experience the biggest issue with the gears sticking is due to "elephant foot" on the first layer. I used to use a raft to fix this but my new printer is tuned well enough to print the first layer accurately.

**Comment by gearfinity** [comment]
Yeah, I just checked and I do have a 0.10 mm tolerance option here:

[_all_parts/planetary_gear_core_5-2S10.STL](https://github.com/gearfinity/gearfinity/blob/main/_all_parts/planetary_gear_core_5-2S10.STL)

Of course that's in the wrong direction for your case 😅 (the 0.15 mm is usually pretty loose for me)

I'll see if I can add a 0.20 mm option as well.

**Comment by gearfinity** [comment]
Done! Just added the 3MF:

https://github.com/gearfinity/gearfinity/blob/main/_all_parts/planetary_gear_core_5-2S15.3MF

I tested it out in prusaslicer and scaling each gear individually (in the xy plane only, centered around the individual gear/object) seemed to work great (however I didn't verify slicing or printing).

If you get a chance to play with this I would love to hear how it goes!
